"""empty message

Revision ID: 416ca8404cdc
Revises: 87bfffd9034a
Create Date: 2017-01-13 14:37:31.826333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416ca8404cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
