"""empty message

Revision ID: 57468b79ce69
Revises: a1e97e44d54f
Create Date: 2016-12-23 09:43:17.025748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57468b79ce69'
down_revision = 'a1e97e44d54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
