"""empty message

Revision ID: 87bfffd9034a
Revises: 7ae41f49341b
Create Date: 2017-01-04 12:45:40.954608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bfffd9034a'
down_revision = '7ae41f49341b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('projects', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'projects')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'experience')
    # ### end Alembic commands ###
