"""empty message

Revision ID: 8abcf8a389e3
Revises: f9a2cb2f6578
Create Date: 2017-01-04 11:48:50.390097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abcf8a389e3'
down_revision = 'f9a2cb2f6578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github')
    # ### end Alembic commands ###
