"""empty message

Revision ID: a1a6905d0d6c
Revises: 87bfffd9034a
Create Date: 2017-01-13 15:12:35.236271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a6905d0d6c'
down_revision = '87bfffd9034a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
